# Constants for cities and positions
POSITIONS = {
    "GENÈVE": (6.14, 46.20),
    "PARIS": (2.35, 48.85),
    "LONDON": (-0.13, 51.51),
    "ROMA": (12.50, 41.90),
    "WIEN": (16.37, 48.21),
    "BUDAPEST": (19.04, 47.50),
    "PRAHA": (14.43, 50.08),
    "BERLIN": (13.40, 52.52),
    "HAMBURG": (10.00, 53.55),
    "AMSTERDAM": (4.89, 52.37),
    "DUBLIN": (-6.26, 53.35),
    "MADRID": (-3.70, 40.42),
    "LISBOA": (-9.14, 38.72),
    "BUCUREȘTI": (26.10, 44.43),
    "SOFIA": (23.32, 42.70),
    "ATHÍNA": (23.73, 37.98),
    "GLASGOW": (-4.25, 55.86),
    "KØBENHAVN": (12.57, 55.68),
    "STOCKHOLM": (18.07, 59.33),
    "HELSINKI": (24.94, 60.17),
    "WARSZAWA": (21.01, 52.23),
    "MOSKVA": (37.62, 55.75),
    "MINSK": (27.56, 53.90),
    "KYIV": (30.52, 50.45),
}


COLORS = {
    "GENÈVE": "YELLOW",
    "PARIS": "BLUE",
    "LONDON": "BLUE",
    "ROMA": "YELLOW",
    "WIEN": "YELLOW",
    "BUDAPEST": "YELLOW",
    "PRAHA": "BLUE",
    "BERLIN": "BLUE",
    "HAMBURG": "BLUE",
    "AMSTERDAM": "BLUE",
    "DUBLIN": "BLUE",
    "MADRID": "YELLOW",
    "LISBOA": "YELLOW",
    "BUCUREȘTI": "RED",
    "SOFIA": "YELLOW",
    "ATHÍNA": "YELLOW",
    "GLASGOW": "BLUE",
    "KØBENHAVN": "RED",
    "STOCKHOLM": "RED",
    "HELSINKI": "RED",
    "WARSZAWA": "RED",
    "MOSKVA": "RED",
    "MINSK": "RED",
    "KYIV": "RED",
}


CITIES = {
    "GENÈVE": ["MADRID", "PARIS", "PRAHA", "WIEN", "ROMA"],
    "PARIS": ["MADRID", "LONDON", "AMSTERDAM", "BERLIN", "GENÈVE"],
    "LONDON": ["DUBLIN", "GLASGOW", "AMSTERDAM", "PARIS"],
    "ROMA": ["GENÈVE", "WIEN", "ATHÍNA"],
    "WIEN": ["GENÈVE", "PRAHA", "BUDAPEST", "SOFIA", "ROMA"],
    "BUDAPEST": ["WIEN", "MINSK", "SOFIA"],
    "PRAHA": ["GENÈVE", "BERLIN", "WARSZAWA", "WIEN"],
    "BERLIN": ["PARIS", "HAMBURG", "WARSZAWA", "PRAHA"],
    "HAMBURG": ["AMSTERDAM", "KØBENHAVN", "BERLIN"],
    "AMSTERDAM": ["LONDON", "HAMBURG", "PARIS"],
    "DUBLIN": ["LONDON", "GLASGOW"],
    "MADRID": ["GENÈVE", "LISBOA", "PARIS"],
    "LISBOA": ["MADRID"],
    "BUCUREȘTI": ["ATHÍNA", "SOFIA", "KYIV"],
    "SOFIA": ["BUCUREȘTI", "ATHÍNA", "WIEN", "BUDAPEST"],
    "ATHÍNA": ["ROMA", "SOFIA", "BUCUREȘTI"],
    "GLASGOW": ["DUBLIN", "LONDON"],
    "KØBENHAVN": ["HAMBURG", "STOCKHOLM", "WARSZAWA"],
    "STOCKHOLM": ["KØBENHAVN", "HELSINKI", "WARSZAWA"],
    "HELSINKI": ["STOCKHOLM", "MOSKVA"],
    "WARSZAWA": ["PRAHA", "BERLIN", "KØBENHAVN", "STOCKHOLM", "MINSK"],
    "MOSKVA": ["KYIV", "MINSK", "HELSINKI"],
    "MINSK": ["KYIV", "BUDAPEST", "WARSZAWA", "MOSKVA"],
    "KYIV": ["MINSK", "MOSKVA", "BUCUREȘTI"],
}